services:
  - type: web
    name: random-video-chat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
